# Generated by Django 4.1.4 on 2022-12-21 06:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_section_chord_category_chord_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='chord',
            name='content',
            field=ckeditor.fields.RichTextField(default=None),
        ),
    ]
