# Generated by Django 4.1.4 on 2022-12-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_chord_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chord',
            name='song_lang',
            field=models.CharField(choices=[('NEPALI', 'NEPALI'), ('HINDI', 'HINDI'), ('ENGLISH', 'ENGLISH')], default=None, max_length=200),
        ),
    ]
