# Generated by Django 4.1.4 on 2022-12-21 09:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_chord_song_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chord',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
