# Generated by Django 4.1.4 on 2022-12-24 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_chord_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chord',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.section'),
        ),
    ]
