# Generated by Django 4.1.4 on 2022-12-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_chord_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_Song_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=20)),
                ('request_song', models.TextField(max_length=300)),
            ],
            options={
                'db_table': 'Request Song',
            },
        ),
    ]
