# Generated by Django 4.1.4 on 2022-12-25 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_request_song_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_song_form',
            name='email',
        ),
    ]
