# Generated by Django 4.1.4 on 2022-12-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_request_song_form_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_song_form',
            name='email',
            field=models.EmailField(default=None, max_length=20),
        ),
    ]
