# Generated by Django 4.1.4 on 2022-12-26 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_request_song_form_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request_Song_Form',
        ),
    ]
