# Generated by Django 4.1.4 on 2022-12-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_request_song_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('request_song', models.TextField(max_length=300)),
                ('email', models.EmailField(default=None, max_length=40)),
            ],
            options={
                'db_table': 'Request',
            },
        ),
    ]
