# Generated by Django 4.1.4 on 2022-12-26 08:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chord',
            name='song_lang',
        ),
        migrations.RemoveField(
            model_name='request',
            name='email',
        ),
        migrations.AddField(
            model_name='chord',
            name='chord',
            field=ckeditor.fields.RichTextField(default=None),
        ),
    ]
