# Generated by Django 4.1.4 on 2022-12-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_chord_song_lang_remove_request_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chord',
            name='strumming',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
