# Generated by Django 4.1.4 on 2022-12-27 16:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_chord_strumming'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chord',
            name='chord',
        ),
        migrations.RemoveField(
            model_name='chord',
            name='html_keyword',
        ),
        migrations.RemoveField(
            model_name='chord',
            name='strumming',
        ),
        migrations.AddField(
            model_name='chord',
            name='html_title_keyword',
            field=models.CharField(default=None, max_length=58),
        ),
        migrations.AlterField(
            model_name='chord',
            name='about',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='chord',
            name='html_description',
            field=models.CharField(max_length=160),
        ),
    ]
