# Generated by Django 4.1.4 on 2022-12-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_chord_chord_remove_chord_html_keyword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chord',
            name='about',
            field=models.TextField(max_length=700),
        ),
    ]
