# Generated by Django 4.1.4 on 2023-01-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='chord',
            name='alt_keyword',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
